// Generated by BUCKLESCRIPT VERSION 1.8.3, PLEASE EDIT WITH CARE
'use strict';

var Jest     = require("bs-jest/lib/js/src/jest.js");
var Revamp   = require("../src/revamp.js");
var Sequence = require("../src/sequence.js");

var re = Revamp.compile(/* None */0, "(an)+([^d])");

describe("compile", (function () {
        return /* () */0;
      }));

describe("matches", (function () {
        Jest.test("match", (function () {
                return Jest.Expect[/* toEqual */11](/* :: */[
                              "ang",
                              /* :: */[
                                "anana",
                                /* [] */0
                              ]
                            ])(Jest.Expect[/* expect */0](Sequence.toList(Revamp.matches("mangos and bananas", re))));
              }));
        return Jest.test("no match", (function () {
                      return Jest.Expect[/* toEqual */11](/* [] */0)(Jest.Expect[/* expect */0](Sequence.toList(Revamp.matches("apples and pears", re))));
                    }));
      }));

describe("indices", (function () {
        Jest.test("match", (function () {
                return Jest.Expect[/* toEqual */11](/* :: */[
                              /* tuple */[
                                1,
                                4
                              ],
                              /* :: */[
                                /* tuple */[
                                  12,
                                  17
                                ],
                                /* [] */0
                              ]
                            ])(Jest.Expect[/* expect */0](Sequence.toList(Revamp.indices("mangos and bananas", re))));
              }));
        return Jest.test("no match", (function () {
                      return Jest.Expect[/* toEqual */11](/* [] */0)(Jest.Expect[/* expect */0](Sequence.toList(Revamp.indices("apples and pears", re))));
                    }));
      }));

describe("captures", (function () {
        Jest.test("match", (function () {
                return Jest.Expect[/* toEqual */11](/* :: */[
                              /* array */[
                                "an",
                                "g"
                              ],
                              /* :: */[
                                /* array */[
                                  "an",
                                  "a"
                                ],
                                /* [] */0
                              ]
                            ])(Jest.Expect[/* expect */0](Sequence.toList(Revamp.captures("mangos and bananas", re))));
              }));
        return Jest.test("no match", (function () {
                      return Jest.Expect[/* toEqual */11](/* [] */0)(Jest.Expect[/* expect */0](Sequence.toList(Revamp.captures("apples and pears", re))));
                    }));
      }));

describe("test", (function () {
        Jest.test("match", (function () {
                return Jest.Expect[/* toBe */1](/* true */1)(Jest.Expect[/* expect */0](Revamp.test("mangos and bananas", re)));
              }));
        return Jest.test("no match", (function () {
                      return Jest.Expect[/* toBe */1](/* false */0)(Jest.Expect[/* expect */0](Revamp.test("apples and pears", re)));
                    }));
      }));

describe("count", (function () {
        Jest.test("match", (function () {
                return Jest.Expect[/* toBe */1](2)(Jest.Expect[/* expect */0](Revamp.count("mangos and bananas", re)));
              }));
        return Jest.test("no match", (function () {
                      return Jest.Expect[/* toBe */1](0)(Jest.Expect[/* expect */0](Revamp.count("apples and pears", re)));
                    }));
      }));

describe("find", (function () {
        Jest.test("match", (function () {
                return Jest.Expect[/* toEqual */11](/* Some */["ang"])(Jest.Expect[/* expect */0](Revamp.find("mangos and bananas", re)));
              }));
        return Jest.test("no match", (function () {
                      return Jest.Expect[/* toBe */1](/* None */0)(Jest.Expect[/* expect */0](Revamp.find("apples and pears", re)));
                    }));
      }));

describe("findIndex", (function () {
        Jest.test("match", (function () {
                return Jest.Expect[/* toEqual */11](/* Some */[/* tuple */[
                                1,
                                4
                              ]])(Jest.Expect[/* expect */0](Revamp.findIndex("mangos and bananas", re)));
              }));
        return Jest.test("no match", (function () {
                      return Jest.Expect[/* toBe */1](/* None */0)(Jest.Expect[/* expect */0](Revamp.findIndex("apples and pears", re)));
                    }));
      }));

describe("replace", (function () {
        Jest.test("match", (function () {
                return Jest.Expect[/* toEqual */11]("mfooos and bfoos")(Jest.Expect[/* expect */0](Revamp.replace((function () {
                                      return "foo";
                                    }), "mangos and bananas", re)));
              }));
        Jest.test("no match", (function () {
                return Jest.Expect[/* toEqual */11]("apples and pears")(Jest.Expect[/* expect */0](Revamp.replace((function () {
                                      return "foo";
                                    }), "apples and pears", re)));
              }));
        return Jest.test("capture", (function () {
                      return Jest.Expect[/* toEqual */11]("mfooos and bfoos")(Jest.Expect[/* expect */0](Revamp.replace((function () {
                                            return "[$1]";
                                          }), "mangos and bananas", re)));
                    }));
      }));

describe("split", (function () {
        var re = Revamp.compile(/* None */0, " |!");
        Jest.test("match", (function () {
                return Jest.Expect[/* toEqual */11](/* array */[
                              "bang",
                              "bang",
                              "bananabatman",
                              ""
                            ])(Jest.Expect[/* expect */0](Revamp.split("bang bang bananabatman!", re)));
              }));
        return Jest.test("no match", (function () {
                      return Jest.Expect[/* toEqual */11](/* array */["apples"])(Jest.Expect[/* expect */0](Revamp.split("apples", re)));
                    }));
      }));

exports.re = re;
/* re Not a pure module */
