// Generated by BUCKLESCRIPT VERSION 1.8.3, PLEASE EDIT WITH CARE
'use strict';

var Jest     = require("bs-jest/lib/js/src/jest.js");
var Sequence = require("../src/sequence.js");

function seq() {
  return /* Cons */[
          876,
          (function () {
              return /* Cons */[
                      564,
                      (function () {
                          return /* Nil */0;
                        })
                    ];
            })
        ];
}

describe("forEach", (function () {
        return Jest.test("...", (function () {
                      var results = /* array */[];
                      Sequence.forEach((function (elt) {
                              return results.push(elt);
                            }), seq);
                      return Jest.Expect[/* toEqual */11](/* int array */[
                                    876,
                                    564
                                  ])(Jest.Expect[/* expect */0](results));
                    }));
      }));

exports.seq = seq;
/*  Not a pure module */
