// Generated by BUCKLESCRIPT VERSION 1.8.3, PLEASE EDIT WITH CARE
'use strict';

var Revamp   = require("../src/revamp.js");
var Sequence = require("../src/sequence.js");

Sequence.forEach((function (m) {
        console.log(m);
        return /* () */0;
      }), Revamp.matches("(na)+", /* Some */[/* :: */[
            /* IgnoreCase */0,
            /* [] */0
          ]], "baNAna"));

/*  Not a pure module */
